config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :home
  resources :issues
  resources :projects
  get '/member/:id', to: 'users#show', as: 'member'
  get '/member', to: 'users#index', as: 'members'
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #I18n
  before_action :set_locale
  def set_locale
    # 可以將 ["en", "zh-TW"] 設定為 VALID_LANG 放到 config/environment.rb 中
    if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
      session[:locale] = params[:locale]
    end
    I18n.locale = session[:locale] || I18n.default_locale
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:show]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all.reverse
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:project, :title, :context, :asker, :developer, :status, :priority)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def index
        redirect_to member_path( current_user.id )
    end
    def show
        @my = User.find( params[:id] )
        @its_me = current_user.id == @my.id
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def issue_status_text( input_num )
        case input_num
        when 0
            t('issues.status_number.unconfirmed')
        when 1
            t('issues.status_number.confirmed')
        when 2
            t('issues.status_number.fixed')
        when 3
            t('issues.status_number.wontfix')
        when 4
            t('issues.status_number.noreproduce')
        when "list"
            "1: #{t('issues.status_number.noreproduce')}"
        else
            t('issues.status_number.other')
        end
    end

    def status_list
        return [[ t('issues.status_number.unconfirmed') , 0 ],
        [ t('issues.status_number.confirmed') , 1 ],
        [ t('issues.status_number.fixed') , 2 ],
        [ t('issues.status_number.wontfix') , 3 ],
        [ t('issues.status_number.noreproduce') , 4 ],
        [ t('issues.status_number.other') , 5 ]]
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Hello</h1>

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true, html:({class:"ts form"})) do |form| %>
  <% if issue.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>
    <ul>
    <% issue.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="fields">
    <div class="six wide field">
      <%= form.label :title , t('issues.items.title') %>
      <%= form.text_field :title, id: :issue_title %>
    </div>

    <div class="four wide field">
      <%= form.label :project , t('issues.items.project') %>
      <%= form.text_field :project, id: :issue_project %>
      <small> 目前一個錯誤只能註冊一個專案。 </small>
    </div>

    <div class="three wide field">
      <%= form.label :status , t('issues.items.status') %>
      <%= form.select( :status, status_list() , select: 0 ) %>
      <small class="status_help" hidden>
        <a href="#">
          <i class="help circle icon"></i> 點選此連結以取得狀態說明。
        </a>
      </small>
      <!-- id="issue_status" name="issue[status]" /> -->
    </div>

    <div class="three wide field">
      <%= form.label :priority , t('issues.items.priority') %>
      <%= form.number_field :priority, id: :issue_priority %>
      <small>
        優先順序以 1 最大逐次遞減。<br />0 為尚未排序。
      </small>
    </div>
  </div>

  <div class="field">
    <%= form.label :context , t('issues.items.context') %>
    <%= form.text_area :context, id: :issue_context %>
  </div>

  <div class="fields">
    <div class="eight wide field">
      <%= form.label :asker , t('issues.items.asker') %>
      <%= form.text_field :asker, id: :issue_asker %>
    </div>
    <div class="eight wide field">
      <%= form.label :developer , t('issues.items.developer') %>
      <%= form.text_field :developer, id: :issue_developer %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit t('issues.action.submit'), class:"ts primary button" %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1><%= t('issues.action.edit') %></h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h1><%= t('issues.title') %></h1>

<table class="ts very basic table">
  <thead>
    <tr>
      <th><%= "ID" %></th>
      <th><%= t('issues.items.title') %></th>
      <th><%= t('issues.items.project') %></th>
      <th><%= t('issues.items.status') %></th>
      <th><%= t('issues.items.priority') %></th>
      <% if current_user %>
      <th colspan="2">
        <%= t('issues.action.item') %>
        <%= link_to t('issues.action.add'), new_issue_path , class: "ts positive basic mini button" %>
      </th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.id %></td>
        <td><%= link_to issue.title, issue %></td>
        <td><%= issue.project %></td>
        <td><%= issue_status_text(issue.status) %></td>
        <td><%= issue.priority %></td>
        <% if current_user %>
        <td><%= link_to t('issues.action.edit'), edit_issue_path(issue) %></td>
        <td><%= link_to t('issues.action.destroy.item'), issue, method: :delete, data: { confirm: t('issues.action.destroy.confirm') } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/issues/new.html.erb
<h1><%= t('issues.action.add') %></h1>

<%= render 'form', issue: @issue %>

<%#= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<h1 class="ts massive dividing header">
    <span class="sub header">
        <%= t'issues.number', num: @issue.id %>
    </span>
    <%= @issue.title %>
</h1>

<div class="ts grid">
    <div class="two column row">
        <div class="column">
            <h2 class="ts medium header">
                <%= t('issues.items.project') %>
                <span class="sub header"> <%= @issue.project %> </span>
            </h2>
        </div>
        <div class="column">
            <h2 class="ts medium header">
                <%= t('issues.items.priority') %>
                <span class="sub header"> <%= @issue.priority %> </span>
            </h2>
        </div>
        <div class="column">
            <h2 class="ts medium header">
                <%= t('issues.items.status') %>
                <span class="sub header"> <%= issue_status_text( @issue.status ) %> </span>
            </h2>    
        </div>
    </div>
</div>

<div class="ts divider"></div>

<div class="ts grid">
    <div class="four wide column">
        <h2 class="ts medium header">
            <%= t('issues.items.asker') %>
            <span class="sub header"> <%= @issue.asker %> </span>
        </h2>

        <h2 class="ts medium header">
            <%= t('issues.items.developer') %>
            <span class="sub header"> <%= @issue.developer %> </span>
        </h2>
        
        <%= link_to t('issues.action.edit') , edit_issue_path(@issue) , class: "ts positive button" if current_user %>
    </div>
    <div class="twelve wide column">
        <h2 class="ts massive header">
            <%= t('issues.items.context') %>
        </h2>
        <div>
            <%= simple_format(@issue.context) %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>マツウラ</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield :css %>
</head>

<body>
    <main class="ts container">
        <nav class="ts pointing secondary menu">
            <%= link_to t('navbar.issue-manage'), issues_path , class: "item" %>
            <%#= link_to t('navbar.projs-manage'), issues_path , class: "item" %>
            <%= link_to "User" , member_path( current_user.id ) , class: "item" %> <!-- t('navbar.membr-manage') -->
            
            <div class="right menu">
                <% if current_user %>
                    <%= link_to t('navbar.logout'), destroy_user_session_path , method: :delete , class: "item" %>
                <% else %>
                    <%= link_to t('navbar.login'), new_user_session_path , class: "item" %>
                <% end %>
                <div id="i18n_menu" class="ts item dropdown">
                    <div class="text">
                        <%= t('navbar.language.dropdown') %>
                        <i class="globe icon"></i>
                    </div>
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <%= link_to "台灣正體", { locale: "zh-TW" } , { :class => "item" } %>
                        <%= link_to "中国简体", { locale: "zh-CN" } , { :class => "item" } %>
                        <%= link_to "English", { locale: "en" },{ class: "item" } %>
                        <%= link_to "日本語", { locale: "ja" },{ class: "item" } %>
                    </div>
                </div>
            </div>
        </nav>
        <%
            ts_class = "ts positive message" if notice
            ts_class = "ts negative message" if alert
        %>
        <div class="<%= ts_class %>">
            <%= notice if notice %>
            <%= alert  if alert  %>
        </div>
        <%= yield %>
    </main>
    <footer>
        <div class="ts container">
            <button class="ts close button"></button>
            <%= t("intro.title") %>
        </div>
    </footer>
    <%= javascript_include_tag 'application' %>
    <%= yield :js %>
</body>
</html>

app/views/users/show.html.erb
<h1 class="ts header"> 用戶資料 </h1>

<div class="ts grid">
    <div class="eight wide column">
        <div class="ts primary segment">
            <ul>
                <li> Email: <%= @my.email %> </li>
                <% if @its_me %>
                <li> <%= link_to "更改用戶資料" , edit_user_registration_path  %> </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>